language: php
sudo: false
before_install:
  - composer self-update
install:
  - composer update $COMPOSER_FLAGS
matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
      script: bin/phpunit

    - php: 7.0
      script: bin/phpunit --coverage-clover build/logs/clover.xml
      before_script:
        - mkdir -p build/logs
      after_script:
        - travis_retry php bin/coveralls -v
        - |
          curl --silent https://github.com/kleijnweb/swagger-bundle |\
            grep -oP 'https://camo.githubusercontent.com/[0-9a-z]+/[0-9a-z]+' |\
            xargs curl -X PURGE

    - php: 7.1
      script:
        - bin/phpunit
        - bin/phpcs --standard=PSR2 src tests --ignore=tests/functional/_app/var

  fast_finish: true
