services:
  swagger.hydrator.class_name_resolver:
    class:   KleijnWeb\PhpApi\Descriptions\Hydrator\ClassNameResolver
    arguments: [[]]
    public: false

  swagger.hydrator.date_time_serializer:
    class:   KleijnWeb\PhpApi\Descriptions\Hydrator\DateTimeSerializer
    public: false

  swagger.hydrator:
    class:   KleijnWeb\SwaggerBundle\Hydrator\ObjectHydrator
    arguments: ['@swagger.hydrator.processor.builder']
    public: false

  swagger.hydrator.processor.builder:
    class: KleijnWeb\PhpApi\Descriptions\Hydrator\ProcessorBuilder
    arguments: ['@swagger.hydrator.class_name_resolver', '@swagger.hydrator.date_time_serializer']
    public: false
