services:
  kernel.listener.swagger.view:
    class: KleijnWeb\SwaggerBundle\EventListener\ViewListener
    arguments: ['@swagger.response.factory']
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
    public: true

  kernel.listener.swagger.request:
    class: KleijnWeb\SwaggerBundle\EventListener\RequestListener
    arguments: [ '@swagger.request.processor']
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    public: true
